# Generated by Django 5.2.7 on 2025-10-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, help_text='Shared notes for this session'),
        ),
    ]
