# Generated by Django 5.2.7 on 2025-10-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='end_time',
        ),
    ]
