# Generated by Django 5.2.7 on 2025-10-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_remove_session_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
