# Generated by Django 5.2.7 on 2025-10-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills_to_learn',
            field=models.ManyToManyField(blank=True, related_name='learners', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_to_teach',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='skills.skill'),
        ),
    ]
