# Generated by Django 5.2.7 on 2025-10-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_endorsement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endorsement',
        ),
    ]
